// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-2L2ls00hmkOvtwUDO-bdGVzC9QblSs',
    appId: '1:972058572380:web:cc5dac7a27a455e4389899',
    messagingSenderId: '972058572380',
    projectId: 'food-map-app-fc8e9',
    authDomain: 'food-map-app-fc8e9.firebaseapp.com',
    storageBucket: 'food-map-app-fc8e9.firebasestorage.app',
    measurementId: 'G-THLHVGZWS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLqvfLjfJyLzKlEhAIcapOwwWaL3g1EYg',
    appId: '1:972058572380:android:4dac06c82ef98e2c389899',
    messagingSenderId: '972058572380',
    projectId: 'food-map-app-fc8e9',
    storageBucket: 'food-map-app-fc8e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtANKIP39O4xZ16lrGCG4aUe-h32jz_1A',
    appId: '1:972058572380:ios:20596c76509aba91389899',
    messagingSenderId: '972058572380',
    projectId: 'food-map-app-fc8e9',
    storageBucket: 'food-map-app-fc8e9.firebasestorage.app',
    androidClientId: '972058572380-oc46qsu538st5064laqb112f4s0o11pk.apps.googleusercontent.com',
    iosClientId: '972058572380-9uta3f2sgcvmbnmekjnjng962prtjf1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFoodMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtANKIP39O4xZ16lrGCG4aUe-h32jz_1A',
    appId: '1:972058572380:ios:20596c76509aba91389899',
    messagingSenderId: '972058572380',
    projectId: 'food-map-app-fc8e9',
    storageBucket: 'food-map-app-fc8e9.firebasestorage.app',
    androidClientId: '972058572380-oc46qsu538st5064laqb112f4s0o11pk.apps.googleusercontent.com',
    iosClientId: '972058572380-9uta3f2sgcvmbnmekjnjng962prtjf1u.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFoodMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn-2L2ls00hmkOvtwUDO-bdGVzC9QblSs',
    appId: '1:972058572380:web:8dc86b25857ceacf389899',
    messagingSenderId: '972058572380',
    projectId: 'food-map-app-fc8e9',
    authDomain: 'food-map-app-fc8e9.firebaseapp.com',
    storageBucket: 'food-map-app-fc8e9.firebasestorage.app',
    measurementId: 'G-WCVNWDF92V',
  );
}
